import { BUILDING_TILE } from '../const';
import { BuildingAudio, BuildingIcon, BuildingTexture } from '../types';

import audioBuild from './audio/build.mp3';
import audioDamage1 from './audio/damage_1.mp3';
import audioDamage2 from './audio/damage_2.mp3';
import audioDead from './audio/dead.mp3';
import audioElectro from './audio/electro.mp3';
import audioOver from './audio/over.mp3';
import audioReload from './audio/reload.mp3';
import audioRepair from './audio/repair.mp3';
import audioSelect from './audio/select.mp3';
import audioUnselect from './audio/unselect.mp3';
import audioUpgrade from './audio/upgrade.mp3';
import iconAlert from './icons/alert.png';
import iconConfirm from './icons/confirm.png';
import iconConfirmDisabled from './icons/confirm_disabled.png';
import iconDecline from './icons/decline.png';
import iconParamAmmo from './icons/params/ammo.png';
import iconParamDamage from './icons/params/damage.png';
import iconParamDelay from './icons/params/delay.png';
import iconParamFreeze from './icons/params/freeze.png';
import iconParamPower from './icons/params/power.png';
import iconParamSpeed from './icons/params/speed.png';
import iconUpgrade from './icons/upgrade.png';
import textureAmmunition from './textures/ammunition.png';
import textureBooster from './textures/booster.png';
import textureGenerator from './textures/generator.png';
import textureRadar from './textures/radar.png';
import textureTowerElectro from './textures/tower_electro.png';
import textureTowerFire from './textures/tower_fire.png';
import textureTowerFrozen from './textures/tower_frozen.png';
import textureTowerLazer from './textures/tower_lazer.png';
import textureWall from './textures/wall.png';

import { Assets } from '~core/assets';

Assets.AddAudio(BuildingAudio.BUILD, audioBuild);
Assets.AddAudio(BuildingAudio.DAMAGE_1, audioDamage1);
Assets.AddAudio(BuildingAudio.DAMAGE_2, audioDamage2);
Assets.AddAudio(BuildingAudio.DEAD, audioDead);
Assets.AddAudio(BuildingAudio.ELECTRO, audioElectro);
Assets.AddAudio(BuildingAudio.OVER, audioOver);
Assets.AddAudio(BuildingAudio.RELOAD, audioReload);
Assets.AddAudio(BuildingAudio.REPAIR, audioRepair);
Assets.AddAudio(BuildingAudio.SELECT, audioSelect);
Assets.AddAudio(BuildingAudio.UNSELECT, audioUnselect);
Assets.AddAudio(BuildingAudio.UPGRADE, audioUpgrade);

Assets.AddImage(BuildingIcon.ALERT, iconAlert);
Assets.AddImage(BuildingIcon.CONFIRM, iconConfirm);
Assets.AddImage(BuildingIcon.CONFIRM_DISABLED, iconConfirmDisabled);
Assets.AddImage(BuildingIcon.UPGRADE, iconUpgrade);
Assets.AddImage(BuildingIcon.AMMO, iconParamAmmo);
Assets.AddImage(BuildingIcon.DAMAGE, iconParamDamage);
Assets.AddImage(BuildingIcon.DECLINE, iconDecline);
Assets.AddImage(BuildingIcon.DELAY, iconParamDelay);
Assets.AddImage(BuildingIcon.FREEZE, iconParamFreeze);
Assets.AddImage(BuildingIcon.POWER, iconParamPower);
Assets.AddImage(BuildingIcon.SPEED, iconParamSpeed);

Assets.AddSprite(BuildingTexture.AMMUNITION, textureAmmunition, BUILDING_TILE);
Assets.AddSprite(BuildingTexture.BOOSTER, textureBooster, BUILDING_TILE);
Assets.AddSprite(BuildingTexture.GENERATOR, textureGenerator, BUILDING_TILE);
Assets.AddSprite(BuildingTexture.RADAR, textureRadar, BUILDING_TILE);
Assets.AddSprite(BuildingTexture.TOWER_ELECTRO, textureTowerElectro, BUILDING_TILE);
Assets.AddSprite(BuildingTexture.TOWER_FIRE, textureTowerFire, BUILDING_TILE);
Assets.AddSprite(BuildingTexture.TOWER_FROZEN, textureTowerFrozen, BUILDING_TILE);
Assets.AddSprite(BuildingTexture.TOWER_LAZER, textureTowerLazer, BUILDING_TILE);
Assets.AddSprite(BuildingTexture.WALL, textureWall, BUILDING_TILE);
